services:
    _defaults:
        autoconfigure: true
        autowire: true

    Terminal42\ChangeLanguage\EventListener\DataContainer\UserLabelsListener: ~

    Terminal42\ChangeLanguage\Migration\CustomLanguageTextMigration: ~
